# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8851385241c81f02332bd4977af16459bbd3e2b030273e7e2d064705c667c42ce5c73602bd7b517f907a6361d3b8915864858a84660f8fccf244a8c513db5b0
test:
  secret_key_base: 2713cc64cafb1d5260ab4cc5e7548a50e14a31d678d3d8f0c8512ef26fcca0b350378d50c56f15e45ba940a4d026afca13354104157886069d391cfb9810bd94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
